### PR TITLE
Added Michał

### PR DESCRIPTION
**Pull request by mgajda**
Hi,
I have added myself, and am open to mentor the attached projects.

### CODE REVIEW

**Comment by Mikolaj** [comment]
Hi @mgajda! Copy-pasto. You added me a second time. :)

**Comment by Mikolaj** [comment]
@willbasky: ^^^ :)

**Comment by willbasky** [comment]
@Mikolaj don't you mind i union them?

**Comment by Mikolaj** [comment]
@willbasky: the correct fix is to change "Mikolaj Konarski" to "Michal Gajda" in the last row (but not the previous one!), which is the action Michal misssed after copy-pasting my row. :)

**Comment by willbasky** [comment]
:))) funny! Will fix!

**Comment by willbasky** [comment]
Done, good?

**Comment by Mikolaj** [comment]
Perfect now, both on .io and in README.md.

Thank you again! Cheers!

**Pull request merged**
